// Garaad marketing site — locked content. Prices live here, keyed by currency,
// never inline in a component. Strings would live in locales/{en,so,ar}.json in
// production; this kit ships English only.
window.GaraadSite = {
  brand: 'Garaad',
  currencies: { USD: '$', EUR: '€', GBP: '£' },
  prices: {
    one: { USD: '$80', EUR: '€70', GBP: '£60' },
    two: { USD: '$70', EUR: '€60', GBP: '£50' },
    twoTotal: { USD: '$140', EUR: '€120', GBP: '£100' },
    saving: { USD: 'Save $10 per child, every month.', EUR: 'Save €10 per child, every month.', GBP: 'Save £10 per child, every month.' },
  },
  nav: ['How it works', 'What we teach', 'Dhaqan', 'Teachers', 'Pricing', 'Safeguarding', 'FAQ'],
  // Somali words used in the interface. Always glossed in English on first use,
  // never as the only label on a control. See readme CONTENT FUNDAMENTALS.
  somali: {
    welcome: 'Soo dhawoow',
    culture: 'Dhaqan',
    history: 'Taariikh',
    poetry: 'Gabay',
    sayings: 'Maahmaah',
    five: 'Shanta Soomaaliyeed',
  },
  includes: [
    'Matched verified teacher',
    'Live one-to-one video lessons',
    'Homework set and marked by the teacher',
    'Somali history, gabay and maahmaah woven into every term',
    'AI study buddy for practice between lessons',
    'A monthly progress report',
    'Free re-match within 48 hours',
  ],
  tracks: [
    { title: 'Somali language', accent: 'blue', icon: 'book-open',
      promise: 'Speaking, reading and writing Somali — from first words to full conversations.',
      bullets: ['Everyday conversation with family', 'Reading and writing the Somali alphabet', 'Sheekooyin, gabay and maahmaah — stories, poetry and sayings'],
      ages: 'Ages 5–15 · Complete beginners welcome' },
    { title: 'Arabic', accent: 'blue', icon: 'file-text',
      promise: 'Modern Standard Arabic, taught right-to-left from day one.',
      bullets: ['The Arabic alphabet and letter forms', 'Reading fluency and vocabulary', 'Grammar foundations that support Qur’aan study'],
      ages: 'Ages 6–15 · Beginner to intermediate' },
    { title: "Qur'aan", accent: 'gold', icon: 'star',
      promise: 'Recitation, tajwiid and memorisation with a qualified teacher.',
      bullets: ['Correct recitation and tajwiid rules', 'Memorisation, tracked surah by surah', 'Meaning and reflection, age-appropriate'],
      ages: 'Ages 5–15 · Assessed only by a human teacher, never by AI' },
  ],
  dhaqan: [
    { so: 'Taariikh', en: 'History', body: 'Where the family comes from, told at a level a child can hold: the sultanates, the poets, the pastoral life, and the journey that brought their parents here.' },
    { so: 'Gabay', en: 'Poetry', body: 'Somalis are called a nation of poets. Children learn to hear the metre, memorise short verses, and recite them out loud without embarrassment.' },
    { so: 'Maahmaah', en: 'Sayings', body: 'The proverbs that carry how Somalis think. A child who knows fifty maahmaah understands far more than fifty sentences.' },
  ],
  maahmaah: { so: "Aqoon la'aan waa iftiin la'aan.", en: 'To be without knowledge is to be without light.' },
  howItWorks: [
    { title: 'Tell us about your child', body: 'Two minutes, and first names only.' },
    { title: 'We match you with a verified teacher', body: 'Within 24 hours.' },
    { title: 'Free 1-hour first lesson', body: 'A real lesson with a real teacher. No charge, no card.' },
    { title: 'Choose a package and keep going', body: 'Or not. Nothing is charged either way.' },
  ],
  vetting: [
    { title: 'Identity verified', body: 'Government ID and right to work checked.', icon: 'user-check' },
    { title: 'Two references taken', body: 'From previous teaching or community roles.', icon: 'file-check' },
    { title: 'Background check', body: 'Where available in the teacher’s country.', icon: 'globe' },
    { title: 'Observed trial lesson', body: 'A senior teacher sits in and scores it.', icon: 'eye' },
    { title: 'Safeguarding training', body: 'Completed, and a code of conduct signed.', icon: 'heart' },
  ],
  teachers: [
    { name: 'Ustaad Yusuf A.', tracks: ['Somali', "Qur'aan"], years: '9 years', languages: 'Somali, Arabic, English', timezone: 'GMT+3', quote: 'I start with the words a child already hears at home.' },
    { name: 'Macallin Farhia', tracks: ['Somali', 'Arabic'], years: '6 years', languages: 'Somali, English', timezone: 'GMT+1', quote: 'Reading comes faster once the sounds feel familiar.' },
    { name: 'Sheekh Abdirahman', tracks: ["Qur'aan"], years: '12 years', languages: 'Somali, Arabic', timezone: 'GMT+3', quote: 'Slow, correct recitation first. Speed can wait.' },
    { name: 'Macallin Hodan', tracks: ['Somali'], years: '4 years', languages: 'Somali, English, Swedish', timezone: 'GMT+2', state: 'new', quote: 'Children talk more when the lesson feels like home.' },
  ],
  faq: [
    { q: 'Is the first lesson really free?', a: 'Yes — a full hour with a verified teacher, at no cost, with no card needed to book it. If it isn’t right for your child, that’s the end of it.' },
    { q: 'What happens after the free lesson?', a: 'We’ll ask what you thought. If you want to carry on, you pick a package and set a weekly time. If not, nothing is charged.' },
    { q: 'How long is each lesson, and how many do we get?', a: 'One hour, twice a week — around eight hours of one-to-one teaching a month.' },
    { q: 'What if my child doesn’t get on with their teacher?', a: 'Tell us and we’ll re-match within 48 hours, at no cost. Their progress moves with them.' },
    { q: 'Do you teach complete beginners?', a: 'Yes — many of our children start with no Somali at all.' },
    { q: 'What time zones do you cover?', a: 'Our teachers cover UK, European and North American evenings and weekends. Tell us when suits you and we’ll match accordingly.' },
    { q: 'Can I pause or cancel?', a: 'Yes, any time, from your account. No notice period, no cancellation fee.' },
    { q: 'How do you keep my child safe online?', a: 'Every teacher is ID-checked, referenced, background-checked where available, observed teaching, and safeguarding-trained. You hold the account, your child never has their own login, and every AI conversation is visible to you.' },
    { q: 'What do we need to join a lesson?', a: 'A phone, tablet or laptop with a camera, and an internet connection. We send a link — there’s nothing to install.' },
  ],
  footer: [
    { h: 'Learn', items: ['Somali', 'Arabic', "Qur'aan", 'Free first lesson', 'Pricing'] },
    { h: 'Trust', items: ['How we verify teachers', 'Safeguarding', 'Our AI rules', 'Privacy notice'] },
    { h: 'Company', items: ['About', 'Teach with us', 'Contact', 'WhatsApp support'] },
    { h: 'Family', items: ['Sign in', 'Help centre', 'Refund policy', 'Terms'] },
  ],
};
